/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AAtributoExp extends PExp
{
    private PIdPonto _idPonto_;
    private PAtributo _atributo_;
    private TPontoEVirgula _pontoEVirgula_;

    public AAtributoExp()
    {
        // Constructor
    }

    public AAtributoExp(
        @SuppressWarnings("hiding") PIdPonto _idPonto_,
        @SuppressWarnings("hiding") PAtributo _atributo_,
        @SuppressWarnings("hiding") TPontoEVirgula _pontoEVirgula_)
    {
        // Constructor
        setIdPonto(_idPonto_);

        setAtributo(_atributo_);

        setPontoEVirgula(_pontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAtributoExp(
            cloneNode(this._idPonto_),
            cloneNode(this._atributo_),
            cloneNode(this._pontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributoExp(this);
    }

    public PIdPonto getIdPonto()
    {
        return this._idPonto_;
    }

    public void setIdPonto(PIdPonto node)
    {
        if(this._idPonto_ != null)
        {
            this._idPonto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idPonto_ = node;
    }

    public PAtributo getAtributo()
    {
        return this._atributo_;
    }

    public void setAtributo(PAtributo node)
    {
        if(this._atributo_ != null)
        {
            this._atributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributo_ = node;
    }

    public TPontoEVirgula getPontoEVirgula()
    {
        return this._pontoEVirgula_;
    }

    public void setPontoEVirgula(TPontoEVirgula node)
    {
        if(this._pontoEVirgula_ != null)
        {
            this._pontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idPonto_)
            + toString(this._atributo_)
            + toString(this._pontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idPonto_ == child)
        {
            this._idPonto_ = null;
            return;
        }

        if(this._atributo_ == child)
        {
            this._atributo_ = null;
            return;
        }

        if(this._pontoEVirgula_ == child)
        {
            this._pontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idPonto_ == oldChild)
        {
            setIdPonto((PIdPonto) newChild);
            return;
        }

        if(this._atributo_ == oldChild)
        {
            setAtributo((PAtributo) newChild);
            return;
        }

        if(this._pontoEVirgula_ == oldChild)
        {
            setPontoEVirgula((TPontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
