/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ABoolTipoPrimitivo extends PTipoPrimitivo
{
    private TBoleano _boleano_;

    public ABoolTipoPrimitivo()
    {
        // Constructor
    }

    public ABoolTipoPrimitivo(
        @SuppressWarnings("hiding") TBoleano _boleano_)
    {
        // Constructor
        setBoleano(_boleano_);

    }

    @Override
    public Object clone()
    {
        return new ABoolTipoPrimitivo(
            cloneNode(this._boleano_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolTipoPrimitivo(this);
    }

    public TBoleano getBoleano()
    {
        return this._boleano_;
    }

    public void setBoleano(TBoleano node)
    {
        if(this._boleano_ != null)
        {
            this._boleano_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boleano_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boleano_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boleano_ == child)
        {
            this._boleano_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boleano_ == oldChild)
        {
            setBoleano((TBoleano) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
