/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoDecFuncao extends PDecFuncao
{
    private TFuncao _funcao_;
    private PTipo _esq_;
    private TIdentificador _esqn_;
    private TParentesesEsquerdo _parentesesEsquerdo_;
    private PListaParametro _mid_;
    private TParentesesDireito _parentesesDireito_;
    private PExp _dir_;

    public ADecFuncaoDecFuncao()
    {
        // Constructor
    }

    public ADecFuncaoDecFuncao(
        @SuppressWarnings("hiding") TFuncao _funcao_,
        @SuppressWarnings("hiding") PTipo _esq_,
        @SuppressWarnings("hiding") TIdentificador _esqn_,
        @SuppressWarnings("hiding") TParentesesEsquerdo _parentesesEsquerdo_,
        @SuppressWarnings("hiding") PListaParametro _mid_,
        @SuppressWarnings("hiding") TParentesesDireito _parentesesDireito_,
        @SuppressWarnings("hiding") PExp _dir_)
    {
        // Constructor
        setFuncao(_funcao_);

        setEsq(_esq_);

        setEsqn(_esqn_);

        setParentesesEsquerdo(_parentesesEsquerdo_);

        setMid(_mid_);

        setParentesesDireito(_parentesesDireito_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoDecFuncao(
            cloneNode(this._funcao_),
            cloneNode(this._esq_),
            cloneNode(this._esqn_),
            cloneNode(this._parentesesEsquerdo_),
            cloneNode(this._mid_),
            cloneNode(this._parentesesDireito_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoDecFuncao(this);
    }

    public TFuncao getFuncao()
    {
        return this._funcao_;
    }

    public void setFuncao(TFuncao node)
    {
        if(this._funcao_ != null)
        {
            this._funcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcao_ = node;
    }

    public PTipo getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PTipo node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public TIdentificador getEsqn()
    {
        return this._esqn_;
    }

    public void setEsqn(TIdentificador node)
    {
        if(this._esqn_ != null)
        {
            this._esqn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqn_ = node;
    }

    public TParentesesEsquerdo getParentesesEsquerdo()
    {
        return this._parentesesEsquerdo_;
    }

    public void setParentesesEsquerdo(TParentesesEsquerdo node)
    {
        if(this._parentesesEsquerdo_ != null)
        {
            this._parentesesEsquerdo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerdo_ = node;
    }

    public PListaParametro getMid()
    {
        return this._mid_;
    }

    public void setMid(PListaParametro node)
    {
        if(this._mid_ != null)
        {
            this._mid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mid_ = node;
    }

    public TParentesesDireito getParentesesDireito()
    {
        return this._parentesesDireito_;
    }

    public void setParentesesDireito(TParentesesDireito node)
    {
        if(this._parentesesDireito_ != null)
        {
            this._parentesesDireito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireito_ = node;
    }

    public PExp getDir()
    {
        return this._dir_;
    }

    public void setDir(PExp node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcao_)
            + toString(this._esq_)
            + toString(this._esqn_)
            + toString(this._parentesesEsquerdo_)
            + toString(this._mid_)
            + toString(this._parentesesDireito_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcao_ == child)
        {
            this._funcao_ = null;
            return;
        }

        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._esqn_ == child)
        {
            this._esqn_ = null;
            return;
        }

        if(this._parentesesEsquerdo_ == child)
        {
            this._parentesesEsquerdo_ = null;
            return;
        }

        if(this._mid_ == child)
        {
            this._mid_ = null;
            return;
        }

        if(this._parentesesDireito_ == child)
        {
            this._parentesesDireito_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcao_ == oldChild)
        {
            setFuncao((TFuncao) newChild);
            return;
        }

        if(this._esq_ == oldChild)
        {
            setEsq((PTipo) newChild);
            return;
        }

        if(this._esqn_ == oldChild)
        {
            setEsqn((TIdentificador) newChild);
            return;
        }

        if(this._parentesesEsquerdo_ == oldChild)
        {
            setParentesesEsquerdo((TParentesesEsquerdo) newChild);
            return;
        }

        if(this._mid_ == oldChild)
        {
            setMid((PListaParametro) newChild);
            return;
        }

        if(this._parentesesDireito_ == oldChild)
        {
            setParentesesDireito((TParentesesDireito) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
