/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecObjDecObj extends PDecObj
{
    private TObjeto _objeto_;
    private PPidClass _esq_;
    private PListaId _dir_;
    private TPontoEVirgula _pontoEVirgula_;

    public ADecObjDecObj()
    {
        // Constructor
    }

    public ADecObjDecObj(
        @SuppressWarnings("hiding") TObjeto _objeto_,
        @SuppressWarnings("hiding") PPidClass _esq_,
        @SuppressWarnings("hiding") PListaId _dir_,
        @SuppressWarnings("hiding") TPontoEVirgula _pontoEVirgula_)
    {
        // Constructor
        setObjeto(_objeto_);

        setEsq(_esq_);

        setDir(_dir_);

        setPontoEVirgula(_pontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ADecObjDecObj(
            cloneNode(this._objeto_),
            cloneNode(this._esq_),
            cloneNode(this._dir_),
            cloneNode(this._pontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObjDecObj(this);
    }

    public TObjeto getObjeto()
    {
        return this._objeto_;
    }

    public void setObjeto(TObjeto node)
    {
        if(this._objeto_ != null)
        {
            this._objeto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objeto_ = node;
    }

    public PPidClass getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PPidClass node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PListaId getDir()
    {
        return this._dir_;
    }

    public void setDir(PListaId node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    public TPontoEVirgula getPontoEVirgula()
    {
        return this._pontoEVirgula_;
    }

    public void setPontoEVirgula(TPontoEVirgula node)
    {
        if(this._pontoEVirgula_ != null)
        {
            this._pontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objeto_)
            + toString(this._esq_)
            + toString(this._dir_)
            + toString(this._pontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objeto_ == child)
        {
            this._objeto_ = null;
            return;
        }

        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        if(this._pontoEVirgula_ == child)
        {
            this._pontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objeto_ == oldChild)
        {
            setObjeto((TObjeto) newChild);
            return;
        }

        if(this._esq_ == oldChild)
        {
            setEsq((PPidClass) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PListaId) newChild);
            return;
        }

        if(this._pontoEVirgula_ == oldChild)
        {
            setPontoEVirgula((TPontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
