/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ADecListaDecs extends PListaDecs
{
    private PDec _dec_;

    public ADecListaDecs()
    {
        // Constructor
    }

    public ADecListaDecs(
        @SuppressWarnings("hiding") PDec _dec_)
    {
        // Constructor
        setDec(_dec_);

    }

    @Override
    public Object clone()
    {
        return new ADecListaDecs(
            cloneNode(this._dec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecListaDecs(this);
    }

    public PDec getDec()
    {
        return this._dec_;
    }

    public void setDec(PDec node)
    {
        if(this._dec_ != null)
        {
            this._dec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dec_ == child)
        {
            this._dec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dec_ == oldChild)
        {
            setDec((PDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
