/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AFilhaRelacaoFilhaRelacao extends PFilhaRelacao
{
    private TFilhaDaClasse _filhaDaClasse_;
    private PPidClass _pidClass_;

    public AFilhaRelacaoFilhaRelacao()
    {
        // Constructor
    }

    public AFilhaRelacaoFilhaRelacao(
        @SuppressWarnings("hiding") TFilhaDaClasse _filhaDaClasse_,
        @SuppressWarnings("hiding") PPidClass _pidClass_)
    {
        // Constructor
        setFilhaDaClasse(_filhaDaClasse_);

        setPidClass(_pidClass_);

    }

    @Override
    public Object clone()
    {
        return new AFilhaRelacaoFilhaRelacao(
            cloneNode(this._filhaDaClasse_),
            cloneNode(this._pidClass_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilhaRelacaoFilhaRelacao(this);
    }

    public TFilhaDaClasse getFilhaDaClasse()
    {
        return this._filhaDaClasse_;
    }

    public void setFilhaDaClasse(TFilhaDaClasse node)
    {
        if(this._filhaDaClasse_ != null)
        {
            this._filhaDaClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filhaDaClasse_ = node;
    }

    public PPidClass getPidClass()
    {
        return this._pidClass_;
    }

    public void setPidClass(PPidClass node)
    {
        if(this._pidClass_ != null)
        {
            this._pidClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pidClass_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._filhaDaClasse_)
            + toString(this._pidClass_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._filhaDaClasse_ == child)
        {
            this._filhaDaClasse_ = null;
            return;
        }

        if(this._pidClass_ == child)
        {
            this._pidClass_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._filhaDaClasse_ == oldChild)
        {
            setFilhaDaClasse((TFilhaDaClasse) newChild);
            return;
        }

        if(this._pidClass_ == oldChild)
        {
            setPidClass((PPidClass) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
