/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AInicializacaoListaInicializacao extends PListaInicializacao
{
    private PPinicializacao _pinicializacao_;

    public AInicializacaoListaInicializacao()
    {
        // Constructor
    }

    public AInicializacaoListaInicializacao(
        @SuppressWarnings("hiding") PPinicializacao _pinicializacao_)
    {
        // Constructor
        setPinicializacao(_pinicializacao_);

    }

    @Override
    public Object clone()
    {
        return new AInicializacaoListaInicializacao(
            cloneNode(this._pinicializacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInicializacaoListaInicializacao(this);
    }

    public PPinicializacao getPinicializacao()
    {
        return this._pinicializacao_;
    }

    public void setPinicializacao(PPinicializacao node)
    {
        if(this._pinicializacao_ != null)
        {
            this._pinicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pinicializacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pinicializacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pinicializacao_ == child)
        {
            this._pinicializacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pinicializacao_ == oldChild)
        {
            setPinicializacao((PPinicializacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
