/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandosListaComandos extends PListaComandos
{
    private PComando _esq_;
    private PListaComandos _dir_;

    public AListaComandosListaComandos()
    {
        // Constructor
    }

    public AListaComandosListaComandos(
        @SuppressWarnings("hiding") PComando _esq_,
        @SuppressWarnings("hiding") PListaComandos _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandosListaComandos(
            cloneNode(this._esq_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandosListaComandos(this);
    }

    public PComando getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PComando node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PListaComandos getDir()
    {
        return this._dir_;
    }

    public void setDir(PListaComandos node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PComando) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PListaComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
