/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AListaRelacaoListaRelacao extends PListaRelacao
{
    private PRelacao _esq_;
    private TOperadorRelacao _operadorRelacao_;
    private PListaRelacao _dir_;

    public AListaRelacaoListaRelacao()
    {
        // Constructor
    }

    public AListaRelacaoListaRelacao(
        @SuppressWarnings("hiding") PRelacao _esq_,
        @SuppressWarnings("hiding") TOperadorRelacao _operadorRelacao_,
        @SuppressWarnings("hiding") PListaRelacao _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setOperadorRelacao(_operadorRelacao_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AListaRelacaoListaRelacao(
            cloneNode(this._esq_),
            cloneNode(this._operadorRelacao_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaRelacaoListaRelacao(this);
    }

    public PRelacao getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PRelacao node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public TOperadorRelacao getOperadorRelacao()
    {
        return this._operadorRelacao_;
    }

    public void setOperadorRelacao(TOperadorRelacao node)
    {
        if(this._operadorRelacao_ != null)
        {
            this._operadorRelacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operadorRelacao_ = node;
    }

    public PListaRelacao getDir()
    {
        return this._dir_;
    }

    public void setDir(PListaRelacao node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._operadorRelacao_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._operadorRelacao_ == child)
        {
            this._operadorRelacao_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PRelacao) newChild);
            return;
        }

        if(this._operadorRelacao_ == oldChild)
        {
            setOperadorRelacao((TOperadorRelacao) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PListaRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
