/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AListaParametroListaParametro extends PListaParametro
{
    private PParametro _esq_;
    private TVirgula _virgula_;
    private PListaParametro _dir_;

    public AListaParametroListaParametro()
    {
        // Constructor
    }

    public AListaParametroListaParametro(
        @SuppressWarnings("hiding") PParametro _esq_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PListaParametro _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setVirgula(_virgula_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AListaParametroListaParametro(
            cloneNode(this._esq_),
            cloneNode(this._virgula_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaParametroListaParametro(this);
    }

    public PParametro getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PParametro node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PListaParametro getDir()
    {
        return this._dir_;
    }

    public void setDir(PListaParametro node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._virgula_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PParametro) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PListaParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
