/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AMetodosMetodos extends PMetodos
{
    private PDec2 _esq_;
    private PMetodos _dir_;

    public AMetodosMetodos()
    {
        // Constructor
    }

    public AMetodosMetodos(
        @SuppressWarnings("hiding") PDec2 _esq_,
        @SuppressWarnings("hiding") PMetodos _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AMetodosMetodos(
            cloneNode(this._esq_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetodosMetodos(this);
    }

    public PDec2 getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PDec2 node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PMetodos getDir()
    {
        return this._dir_;
    }

    public void setDir(PMetodos node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PDec2) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PMetodos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
