/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoRelacao extends PRelacao
{
    private TClasse _classe_;
    private PPidClass _esq_;
    private PFilhaRelacao _dir_;

    public ARelacaoRelacao()
    {
        // Constructor
    }

    public ARelacaoRelacao(
        @SuppressWarnings("hiding") TClasse _classe_,
        @SuppressWarnings("hiding") PPidClass _esq_,
        @SuppressWarnings("hiding") PFilhaRelacao _dir_)
    {
        // Constructor
        setClasse(_classe_);

        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoRelacao(
            cloneNode(this._classe_),
            cloneNode(this._esq_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoRelacao(this);
    }

    public TClasse getClasse()
    {
        return this._classe_;
    }

    public void setClasse(TClasse node)
    {
        if(this._classe_ != null)
        {
            this._classe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classe_ = node;
    }

    public PPidClass getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PPidClass node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PFilhaRelacao getDir()
    {
        return this._dir_;
    }

    public void setDir(PFilhaRelacao node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classe_)
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classe_ == child)
        {
            this._classe_ = null;
            return;
        }

        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classe_ == oldChild)
        {
            setClasse((TClasse) newChild);
            return;
        }

        if(this._esq_ == oldChild)
        {
            setEsq((PPidClass) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PFilhaRelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
