/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.lexer;

import java.io.*;
import jaca.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOperadorRelacao(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoEVirgula(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoleano(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdade(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQ(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParentesesEsquerdo(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParentesesDireito(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicializacao(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasse(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObjeto(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFilhaDaClasse(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoDeEntrada(line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(text, line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdClass(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {33, 33, 4}, {35, 35, 5}, {37, 37, 6}, {38, 38, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {95, 95, 23}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 24}, {101, 101, 27}, {102, 102, 28}, {103, 104, 24}, {105, 105, 29}, {106, 110, 24}, {111, 111, 30}, {112, 112, 31}, {113, 113, 24}, {114, 114, 32}, {115, 115, 33}, {116, 117, 24}, {118, 118, 34}, {119, 122, 24}, {123, 123, 35}, {192, 195, 36}, {199, 199, 37}, {201, 202, 38}, {211, 213, 39}, {218, 218, 40}, {224, 227, 41}, {231, 231, 42}, {233, 234, 43}, {237, 237, 44}, {243, 245, 45}, {250, 250, 46}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {},
            {{10, 10, 47}, {13, 13, 48}, {32, 126, 49}, {128, 254, 50}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{44, 44, 51}, {48, 57, 52}, {69, 69, 53}, {101, 101, 54}, },
            {{61, 61, 55}, },
            {},
            {{61, 61, 56}, },
            {{61, 61, 57}, },
            {{62, 62, 58}, },
            {{65, 90, 22}, {95, 95, 59}, {97, 122, 24}, {192, 250, -2}, },
            {{65, 90, 60}, {95, 95, 59}, {97, 122, 61}, {192, 195, 62}, {199, 199, 63}, {201, 202, 64}, {211, 213, 65}, {218, 218, 66}, {224, 227, 67}, {231, 231, 68}, {233, 234, 69}, {237, 237, 70}, {243, 245, 71}, {250, 250, 72}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 110, 24}, {111, 111, 73}, {112, 122, 24}, {192, 250, -2}, },
            {{65, 95, -24}, {97, 107, 24}, {108, 108, 74}, {109, 110, 24}, {111, 111, 75}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 109, 24}, {110, 110, 76}, {111, 122, 24}, {192, 250, -2}, },
            {{65, 95, -24}, {97, 97, 77}, {98, 104, 24}, {105, 105, 78}, {106, 116, 24}, {117, 117, 79}, {118, 122, 24}, {192, 250, -2}, },
            {{65, 109, -29}, {110, 110, 80}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 97, 24}, {98, 98, 81}, {99, 116, 24}, {117, 117, 82}, {118, 250, -30}, },
            {{65, 95, -24}, {97, 113, 24}, {114, 114, 83}, {115, 122, 24}, {192, 250, -2}, },
            {{65, 95, -24}, {97, 100, 24}, {101, 101, 84}, {102, 122, 24}, {192, 250, -2}, },
            {{65, 100, -34}, {101, 101, 85}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 97, 86}, {98, 100, 24}, {101, 101, 87}, {102, 250, -34}, },
            {{10, 10, 88}, {13, 13, 89}, {32, 124, 90}, {125, 125, 91}, {126, 126, 92}, {128, 254, 93}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{13, 13, 94}, },
            {},
            {{10, 254, -7}, },
            {{10, 254, -7}, },
            {{48, 57, 95}, },
            {{44, 44, 96}, {48, 57, 52}, },
            {{45, 45, 97}, {48, 57, 98}, },
            {{45, 57, -55}, },
            {},
            {},
            {},
            {{62, 62, 99}, },
            {{65, 90, 100}, {95, 95, 59}, {97, 122, 101}, {192, 195, 102}, {199, 199, 103}, {201, 202, 104}, {211, 213, 105}, {218, 218, 106}, {224, 227, 107}, {231, 231, 108}, {233, 234, 109}, {237, 237, 110}, {243, 245, 111}, {250, 250, 112}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 110, -27}, {111, 111, 113}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 114}, {98, 122, 24}, {192, 250, -2}, },
            {{65, 109, -29}, {110, 110, 115}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 112, 24}, {113, 113, 116}, {114, 122, 24}, {192, 250, -2}, },
            {{65, 107, -28}, {108, 108, 117}, {109, 122, 24}, {192, 250, -2}, },
            {{65, 107, -28}, {108, 108, 118}, {109, 109, 119}, {110, 122, 24}, {192, 250, -2}, },
            {{65, 109, -29}, {110, 110, 120}, {111, 250, -29}, },
            {{65, 234, -24}, {237, 237, 121}, {243, 250, -2}, },
            {{65, 95, -24}, {97, 105, 24}, {106, 106, 122}, {107, 122, 24}, {192, 250, -2}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 123}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 124}, {98, 250, -76}, },
            {{65, 109, -29}, {110, 110, 125}, {111, 250, -29}, },
            {{65, 113, -33}, {114, 114, 126}, {115, 250, -33}, },
            {{65, 113, -33}, {114, 114, 127}, {115, 250, -33}, },
            {{10, 10, 88}, {13, 13, 128}, {32, 254, -37}, },
            {{10, 254, -37}, },
            {{10, 254, -37}, },
            {},
            {{10, 254, -37}, },
            {{10, 254, -37}, },
            {},
            {{48, 57, 95}, {69, 101, -18}, },
            {{48, 57, 129}, },
            {{48, 57, 98}, },
            {{48, 57, 98}, },
            {},
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 250, -61}, },
            {{65, 107, -28}, {108, 108, 130}, {109, 250, -79}, },
            {{65, 95, -24}, {97, 114, 24}, {115, 115, 131}, {116, 122, 24}, {192, 250, -2}, },
            {{65, 114, -116}, {115, 115, 132}, {116, 250, -116}, },
            {{65, 95, -24}, {97, 116, 24}, {117, 117, 133}, {118, 250, -30}, },
            {{65, 114, -116}, {115, 115, 134}, {116, 250, -116}, },
            {{65, 95, -24}, {97, 103, 24}, {104, 104, 135}, {105, 122, 24}, {192, 250, -2}, },
            {{65, 250, -24}, },
            {{65, 227, -24}, {231, 231, 136}, {233, 250, -2}, },
            {{65, 95, -24}, {97, 98, 24}, {99, 99, 137}, {100, 122, 24}, {192, 250, -2}, },
            {{65, 100, -34}, {101, 101, 138}, {102, 250, -34}, },
            {{65, 98, -123}, {99, 99, 139}, {100, 250, -123}, },
            {{65, 107, -28}, {108, 108, 140}, {109, 250, -79}, },
            {{65, 218, -24}, {224, 226, 41}, {227, 227, 141}, {231, 250, -2}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 99, 24}, {100, 100, 142}, {101, 122, 24}, {192, 250, -2}, },
            {{10, 254, -37}, },
            {{48, 57, 129}, },
            {{65, 250, -24}, },
            {{65, 114, -116}, {115, 115, 143}, {116, 250, -116}, },
            {{65, 95, -24}, {97, 115, 24}, {116, 116, 144}, {117, 122, 24}, {192, 250, -2}, },
            {{65, 95, -24}, {97, 97, 145}, {98, 250, -76}, },
            {{65, 110, -27}, {111, 111, 146}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 147}, {98, 250, -76}, },
            {{65, 226, -127}, {227, 227, 148}, {231, 250, -2}, },
            {{65, 95, -24}, {97, 104, 24}, {105, 105, 149}, {106, 122, 24}, {192, 250, -2}, },
            {{65, 115, -134}, {116, 116, 150}, {117, 250, -134}, },
            {{65, 100, -34}, {101, 101, 151}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 152}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 153}, {98, 250, -76}, },
            {{65, 100, -34}, {101, 101, 154}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{65, 109, -29}, {110, 110, 155}, {111, 250, -29}, },
            {{65, 250, -24}, },
            {{32, 32, 156}, {65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 157}, {112, 250, -27}, },
            {{65, 110, -27}, {111, 111, 158}, {112, 250, -27}, },
            {{65, 110, -27}, {111, 111, 159}, {112, 250, -27}, },
            {{65, 99, -129}, {100, 100, 160}, {101, 250, -129}, },
            {{65, 250, -24}, },
            {{65, 99, -129}, {100, 100, 161}, {101, 250, -129}, },
            {{65, 250, -24}, },
            {{65, 115, -134}, {116, 116, 162}, {117, 250, -134}, },
            {{100, 100, 163}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 104, -139}, {105, 105, 164}, {106, 250, -139}, },
            {{65, 100, -34}, {101, 101, 165}, {102, 250, -34}, },
            {{65, 110, -27}, {111, 111, 166}, {112, 250, -27}, },
            {{97, 97, 167}, },
            {{65, 95, -24}, {97, 108, 24}, {109, 109, 168}, {110, 250, -80}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{32, 32, 169}, },
            {{65, 100, -34}, {101, 101, 170}, {102, 250, -34}, },
            {{99, 99, 171}, },
            {{65, 109, -29}, {110, 110, 172}, {111, 250, -29}, },
            {{108, 108, 173}, },
            {{65, 115, -134}, {116, 116, 174}, {117, 250, -134}, },
            {{97, 97, 175}, },
            {{65, 110, -27}, {111, 111, 176}, {112, 250, -27}, },
            {{115, 115, 177}, },
            {{65, 250, -24}, },
            {{115, 115, 178}, },
            {{101, 101, 179}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 39, 39, 39, 15, -1, 11, 1, 16, 17, 9, 7, 19, 8, 32, 10, -1, -1, 2, 13, -1, -1, 37, 37, 37, 37, 37, 30, 37, 37, 37, 37, 37, 37, 37, -1, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 35, 35, -1, -1, -1, -1, -1, -1, 18, 14, 12, -1, 37, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 31, 37, 37, 27, 37, 37, -1, -1, -1, 35, -1, -1, 35, 38, -1, -1, 38, 34, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 26, 37, 37, 37, 37, 37, 37, 22, 37, -1, 38, 4, 37, 37, 37, 37, 37, 37, 37, 37, 37, 3, 37, 37, 37, 23, 37, 6, 37, 37, 37, 37, 37, 28, 37, 20, 37, -1, 0, 25, 21, 37, 37, 37, -1, 37, 5, 29, -1, 37, -1, 37, -1, 37, -1, 37, -1, 24, -1, -1, 33, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
